# Generated by Django 5.2.5 on 2025-08-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cnpj', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='CNPJ Básico')),
                ('razao_social', models.CharField(db_index=True, max_length=255, verbose_name='Razão Social')),
                ('natureza_juridica', models.CharField(max_length=4, verbose_name='Natureza Jurídica')),
                ('qualificacao_responsavel', models.CharField(max_length=2, verbose_name='Qualificação do Responsável')),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Capital Social')),
                ('porte_empresa', models.CharField(blank=True, max_length=2, null=True, verbose_name='Porte da Empresa')),
                ('ente_federativo_responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ente Federativo Responsável')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
    ]
